import type { Data } from "../types";
const now = new Date();
const y = now.getFullYear();
const m = now.getMonth() + 1;
const sessionTime = (days: number, hour: number) => {
  const d = new Date();
  d.setDate(d.getDate() + days);
  return new Date(
    `${d.toISOString().slice(0, 10)}T${String(hour).padStart(2, "0")}:00:00+05:30`,
  ).toISOString();
};
export const seed: Data = {
  students: [
    {
      id: "s1",
      student_number: "MA-001",
      full_name: "Nethmi Perera",
      phone: "0771234567",
      guardian_name: "Kumari Perera",
      guardian_phone: "0711234567",
      email: "nethmi@example.test",
      school: "Anula Vidyalaya",
      status: "active",
      account_id: "demo-student",
      created_at: now.toISOString(),
    },
    {
      id: "s2",
      student_number: "MA-002",
      full_name: "කවිඳු සිල්වා",
      phone: "0762345678",
      guardian_name: "Sunil Silva",
      guardian_phone: "0722345678",
      email: "",
      school: "Royal College",
      status: "active",
      account_id: null,
      created_at: now.toISOString(),
    },
    {
      id: "s3",
      student_number: "MA-003",
      full_name: "Ayesha Rahman",
      phone: "0753456789",
      guardian_name: "Fathima Rahman",
      guardian_phone: "0773456789",
      email: "",
      school: "Muslim Ladies College",
      status: "active",
      account_id: null,
      created_at: now.toISOString(),
    },
  ],
  classes: [
    {
      id: "c1",
      name: `O/L ${y + 1} • Theory`,
      exam_year: y + 1,
      type: "Theory",
      delivery_mode: "hybrid",
      monthly_fee: 3500,
      description: "Build strong foundations, one concept at a time.",
      status: "active",
    },
    {
      id: "c2",
      name: `O/L ${y} • Paper practice`,
      exam_year: y,
      type: "Paper",
      delivery_mode: "online",
      monthly_fee: 2500,
      description: "Timed papers and guided marking discussions.",
      status: "active",
    },
    {
      id: "c3",
      name: `O/L ${y} • Revision`,
      exam_year: y,
      type: "Revision",
      delivery_mode: "physical",
      monthly_fee: 3000,
      description: "Focused revision for the final examination.",
      status: "active",
    },
  ],
  enrollments: [
    {
      id: "e1",
      student_id: "s1",
      class_id: "c1",
      start_date: `${y}-01-01`,
      end_date: null,
      status: "active",
    },
    {
      id: "e2",
      student_id: "s1",
      class_id: "c2",
      start_date: `${y}-01-01`,
      end_date: null,
      status: "active",
    },
    {
      id: "e3",
      student_id: "s2",
      class_id: "c1",
      start_date: `${y}-01-01`,
      end_date: null,
      status: "active",
    },
    {
      id: "e4",
      student_id: "s3",
      class_id: "c3",
      start_date: `${y}-01-01`,
      end_date: null,
      status: "active",
    },
  ],
  class_sessions: [
    {
      id: "ss1",
      class_id: "c1",
      starts_at: sessionTime(0, 16),
      ends_at: sessionTime(0, 18),
      delivery_mode: "hybrid",
      location: "Nugegoda classroom • Hall A",
      meeting_url: "https://meet.google.com/",
      status: "scheduled",
    },
    {
      id: "ss2",
      class_id: "c2",
      starts_at: sessionTime(2, 18),
      ends_at: sessionTime(2, 20),
      delivery_mode: "online",
      location: "",
      meeting_url: "https://zoom.us/join",
      status: "scheduled",
    },
    {
      id: "ss3",
      class_id: "c1",
      starts_at: sessionTime(-7, 16),
      ends_at: sessionTime(-7, 18),
      delivery_mode: "physical",
      location: "Hall A",
      meeting_url: "",
      status: "completed",
    },
  ],
  attendance: [
    {
      id: "a1",
      session_id: "ss3",
      enrollment_id: "e1",
      student_id: "s1",
      status: "present",
      updated_at: now.toISOString(),
    },
    {
      id: "a2",
      session_id: "ss3",
      enrollment_id: "e3",
      student_id: "s2",
      status: "late",
      updated_at: now.toISOString(),
    },
  ],
  fee_dues: [
    {
      id: "d1",
      enrollment_id: "e1",
      student_id: "s1",
      class_id: "c1",
      year: y,
      month: m,
      base_amount: 3500,
      amount: 3500,
      adjustment_note: "",
    },
    {
      id: "d2",
      enrollment_id: "e2",
      student_id: "s1",
      class_id: "c2",
      year: y,
      month: m,
      base_amount: 2500,
      amount: 2500,
      adjustment_note: "",
    },
    {
      id: "d3",
      enrollment_id: "e3",
      student_id: "s2",
      class_id: "c1",
      year: y,
      month: m,
      base_amount: 3500,
      amount: 3000,
      adjustment_note: "Sibling discount",
    },
  ],
  payments: [
    {
      id: "p1",
      due_id: "d1",
      amount: 1500,
      method: "cash",
      status: "approved",
      slip_path: null,
      note: "Part payment",
      review_note: "Cash received",
      reviewed_by: "demo-teacher",
      reviewed_at: now.toISOString(),
      created_at: now.toISOString(),
    },
    {
      id: "p2",
      due_id: "d2",
      amount: 2500,
      method: "bank",
      status: "pending",
      slip_path: null,
      note: "Fictional bank transfer; demo has no real slip.",
      review_note: "",
      reviewed_by: null,
      reviewed_at: null,
      created_at: now.toISOString(),
    },
  ],
  payment_voids: [],
  materials: [
    {
      id: "m1",
      class_id: "c1",
      title: "Quadratic equations • Lesson notes",
      topic: "Algebra",
      type: "notes",
      description:
        "Worked examples and practice exercises. Demo placeholder; upload a PDF to try file access.",
      file_path: null,
      external_url: "",
      published_at: now.toISOString(),
      is_published: true,
    },
    {
      id: "m2",
      class_id: "c2",
      title: "Paper discussion recording",
      topic: "Past papers",
      type: "recording",
      description: "Demo external lesson link.",
      file_path: null,
      external_url: "https://www.youtube.com/",
      published_at: now.toISOString(),
      is_published: true,
    },
  ],
  announcements: [
    {
      id: "an1",
      class_id: "c1",
      title: "Bring your geometry instruments",
      message:
        "We will practise construction questions in our next class. Please bring a compass, ruler and protractor.",
      published_at: now.toISOString(),
      expires_at: null,
    },
  ],
  linking_requests: [],
};
