create function public.is_teacher() returns boolean language sql stable security definer set search_path=public as $$ select exists(select 1 from profiles where id=auth.uid() and role='teacher') $$;
create function public.owns_student(sid uuid) returns boolean language sql stable security definer set search_path=public as $$ select exists(select 1 from students where id=sid and account_id=auth.uid() and status='active') $$;
create function public.in_class(cid uuid) returns boolean language sql stable security definer set search_path=public as $$ select exists(select 1 from enrollments e join students s on s.id=e.student_id where e.class_id=cid and s.account_id=auth.uid() and s.status='active' and e.status='active' and e.start_date<=(now() at time zone 'Asia/Colombo')::date and (e.end_date is null or e.end_date>=(now() at time zone 'Asia/Colombo')::date)) $$;
create function public.owns_due(did uuid) returns boolean language sql stable security definer set search_path=public as $$ select exists(select 1 from fee_dues where id=did and owns_student(student_id)) $$;
do $$ declare t text; begin foreach t in array array['profiles','students','classes','enrollments','class_sessions','attendance','fee_dues','payments','payment_voids','materials','announcements','linking_requests','audit_log'] loop execute format('alter table public.%I enable row level security',t); execute format('revoke all on public.%I from anon, authenticated',t); execute format('grant select on public.%I to authenticated',t); end loop; end $$;
create policy profiles_read on public.profiles for select to authenticated using(id=auth.uid() or is_teacher());
create policy students_read on public.students for select to authenticated using(is_teacher() or account_id=auth.uid());
create policy classes_read on public.classes for select to authenticated using(is_teacher() or in_class(id));
create policy enrollments_read on public.enrollments for select to authenticated using(is_teacher() or owns_student(student_id));
create policy sessions_read on public.class_sessions for select to authenticated using(is_teacher() or in_class(class_id));
create policy attendance_read on public.attendance for select to authenticated using(is_teacher() or owns_student(student_id));
create policy dues_read on public.fee_dues for select to authenticated using(is_teacher() or owns_student(student_id));
create policy payments_read on public.payments for select to authenticated using(is_teacher() or owns_due(due_id));
create policy voids_read on public.payment_voids for select to authenticated using(is_teacher() or exists(select 1 from payments p where p.id=payment_id and owns_due(p.due_id)));
create policy materials_read on public.materials for select to authenticated using(is_teacher() or (in_class(class_id) and is_published and published_at<=now()));
create policy announcements_read on public.announcements for select to authenticated using(is_teacher() or (in_class(class_id) and published_at<=now() and (expires_at is null or expires_at>now())));
create policy links_read on public.linking_requests for select to authenticated using(is_teacher() or account_id=auth.uid());
create policy audit_read on public.audit_log for select to authenticated using(is_teacher());
-- Only non-financial operational tables are directly writable by teachers.
do $$ declare t text; begin foreach t in array array['students','classes','enrollments','class_sessions','attendance','materials','announcements'] loop execute format('grant insert,update on public.%I to authenticated',t); execute format('create policy teacher_insert on public.%I for insert to authenticated with check(is_teacher())',t); execute format('create policy teacher_update on public.%I for update to authenticated using(is_teacher()) with check(is_teacher())',t); end loop; end $$;
-- Account identity may be modified only by the verified linking function.
revoke insert,update on public.students from authenticated;
grant insert(student_number,full_name,phone,guardian_name,guardian_phone,email,school,status),update(student_number,full_name,phone,guardian_name,guardian_phone,email,school,status) on public.students to authenticated;
create function public.log_change() returns trigger language plpgsql security definer set search_path=public as $$ begin insert into audit_log(actor_id,action,table_name,record_id) values(auth.uid(),TG_OP,TG_TABLE_NAME,new.id); return new; end $$;
do $$ declare t text; begin foreach t in array array['students','classes','enrollments','class_sessions','attendance','fee_dues','payments','payment_voids','materials','announcements','linking_requests'] loop execute format('create trigger audit_change after insert or update on public.%I for each row execute function public.log_change()',t); end loop; end $$;
create function public.require_teacher() returns void language plpgsql security definer set search_path=public as $$ begin if not is_teacher() then raise exception 'Teacher permission required'; end if; end $$;
create function public.generate_dues(p_year integer,p_month integer) returns integer language plpgsql security definer set search_path=public as $$ declare count_rows integer; first_day date; last_day date; begin perform require_teacher(); first_day=make_date(p_year,p_month,1); last_day=(first_day+interval '1 month - 1 day')::date; insert into fee_dues(enrollment_id,student_id,class_id,year,month,base_amount,amount) select e.id,e.student_id,e.class_id,p_year,p_month,c.monthly_fee,c.monthly_fee from enrollments e join classes c on c.id=e.class_id where e.start_date<=last_day and (e.end_date is null or e.end_date>=first_day) on conflict(enrollment_id,year,month) do nothing; get diagnostics count_rows=row_count; return count_rows; end $$;
create function public.due_balance(p_due_id uuid) returns numeric language sql stable security definer set search_path=public as $$ select d.amount-coalesce((select sum(p.amount) from payments p where p.due_id=d.id and p.status='approved' and not exists(select 1 from payment_voids v where v.payment_id=p.id)),0) from fee_dues d where d.id=p_due_id and (is_teacher() or owns_student(d.student_id)) $$;
create function public.adjust_due(p_due_id uuid,p_amount numeric,p_note text) returns void language plpgsql security definer set search_path=public as $$ declare paid numeric; begin perform require_teacher(); if p_amount<0 or p_amount<>round(p_amount,2) or length(trim(p_note))=0 then raise exception 'Valid amount and adjustment reason required'; end if; perform 1 from fee_dues where id=p_due_id for update; if not found then raise exception 'Due not found'; end if; select coalesce(sum(p.amount),0) into paid from payments p where p.due_id=p_due_id and p.status='approved' and not exists(select 1 from payment_voids v where v.payment_id=p.id); if p_amount<paid then raise exception 'Due cannot be below approved payments'; end if; update fee_dues set amount=p_amount,adjustment_note=p_note where id=p_due_id; end $$;
create function public.record_payment(p_due_id uuid,p_amount numeric,p_method text,p_note text default '',p_slip_path text default null) returns uuid language plpgsql security definer set search_path=public as $$ declare result uuid; teacher boolean; begin teacher=is_teacher(); if auth.uid() is null or (not teacher and not owns_due(p_due_id)) then raise exception 'Payment permission denied'; end if; if p_amount is null or p_amount<=0 or p_amount<>round(p_amount,2) or p_method not in ('cash','bank') then raise exception 'Invalid payment'; end if; perform 1 from fee_dues where id=p_due_id for update; if not found then raise exception 'Due not found'; end if; if p_amount>due_balance(p_due_id) then raise exception 'Payment exceeds outstanding balance'; end if; if not teacher then if p_method<>'bank' or p_slip_path is null or split_part(p_slip_path,'/',1)<>auth.uid()::text or not exists(select 1 from storage.objects where bucket_id='payment-slips' and name=p_slip_path and owner_id=auth.uid()::text) then raise exception 'Upload your own bank slip first'; end if; end if; insert into payments(due_id,amount,method,note,slip_path,status,submitted_by,reviewed_by,reviewed_at) values(p_due_id,p_amount,p_method,p_note,p_slip_path,case when teacher then 'approved' else 'pending' end,auth.uid(),case when teacher then auth.uid() end,case when teacher then now() end) returning id into result; return result; end $$;
create function public.review_payment(p_payment_id uuid,p_approve boolean,p_note text default '') returns void language plpgsql security definer set search_path=public as $$ declare did uuid; p payments; begin perform require_teacher(); select due_id into did from payments where id=p_payment_id; if did is null then raise exception 'Payment not found'; end if; -- Every financial mutation locks the parent due FIRST, serializing concurrent reviews.
 perform 1 from fee_dues where id=did for update; select * into p from payments where id=p_payment_id for update; if p.status<>'pending' then raise exception 'Payment already reviewed'; end if; if p_approve and p.amount>due_balance(did) then raise exception 'Payment exceeds outstanding balance'; end if; if not p_approve and length(trim(p_note))=0 then raise exception 'Rejection reason required'; end if; update payments set status=case when p_approve then 'approved' else 'rejected' end,review_note=p_note,reviewed_by=auth.uid(),reviewed_at=now() where id=p_payment_id; end $$;
create function public.void_payment(p_payment_id uuid,p_reason text) returns void language plpgsql security definer set search_path=public as $$ declare did uuid; begin perform require_teacher(); select due_id into did from payments where id=p_payment_id and status='approved'; if did is null or length(trim(p_reason))=0 then raise exception 'Approved payment and reason required'; end if; perform 1 from fee_dues where id=did for update; insert into payment_voids(payment_id,reason,created_by) values(p_payment_id,p_reason,auth.uid()); end $$;
-- The student initiates a request using a teacher-provided record UUID. This proves
-- control of the signed-in account, not ownership of the record. Teacher verifies
-- guardian/student identity out-of-band before approving; no email matching.
create function public.request_link(p_student_id uuid) returns void language plpgsql security definer set search_path=public as $$ begin if auth.uid() is null or not exists(select 1 from profiles where id=auth.uid() and role='student') then raise exception 'Student account required'; end if; if not exists(select 1 from students where id=p_student_id and account_id is null and status='active') then raise exception 'Record unavailable'; end if; insert into linking_requests(student_id,account_id) values(p_student_id,auth.uid()) on conflict(student_id,account_id) do update set status='pending',reviewed_by=null,reviewed_at=null; end $$;
create function public.review_link(p_request_id uuid,p_approve boolean) returns void language plpgsql security definer set search_path=public as $$ declare r linking_requests; begin perform require_teacher(); select * into r from linking_requests where id=p_request_id for update; if not found or r.status<>'pending' then raise exception 'Request unavailable'; end if; if p_approve then perform 1 from students where id=r.student_id and account_id is null for update; if not found then raise exception 'Student already linked'; end if; if not exists(select 1 from auth.users where id=r.account_id and email_confirmed_at is not null) then raise exception 'Account email must be verified'; end if; if not exists(select 1 from profiles where id=r.account_id and role='student') then raise exception 'Student account required'; end if; update students set account_id=r.account_id where id=r.student_id; end if; update linking_requests set status=case when p_approve then 'approved' else 'rejected' end,reviewed_by=auth.uid(),reviewed_at=now() where id=r.id; end $$;
-- Ended enrollment must retain its end date; attendance must fall inside its dates.
create function public.check_attendance_date() returns trigger language plpgsql set search_path=public as $$ declare session_day date; e enrollments; begin select (starts_at at time zone 'Asia/Colombo')::date into session_day from class_sessions where id=new.session_id; select * into e from enrollments where id=new.enrollment_id; if session_day<e.start_date or (e.end_date is not null and session_day>e.end_date) then raise exception 'Student was not enrolled on session date'; end if; return new; end $$;
create trigger attendance_dates before insert or update on public.attendance for each row execute function public.check_attendance_date();
-- Explicit function grants: helpers returning identities/data are not anonymous APIs.
revoke execute on all functions in schema public from public,anon;
grant execute on function public.is_teacher(),public.owns_student(uuid),public.in_class(uuid),public.owns_due(uuid),public.generate_dues(integer,integer),public.due_balance(uuid),public.adjust_due(uuid,numeric,text),public.record_payment(uuid,numeric,text,text,text),public.review_payment(uuid,boolean,text),public.void_payment(uuid,text),public.request_link(uuid),public.review_link(uuid,boolean) to authenticated;
